// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_e96TZGXvhBeTIZxXrl0LoYga8QsGagU',
    appId: '1:193960592771:web:39ee57b199a91916c5a2b6',
    messagingSenderId: '193960592771',
    projectId: 'students-app-b1fa2',
    authDomain: 'students-app-b1fa2.firebaseapp.com',
    storageBucket: 'students-app-b1fa2.firebasestorage.app',
    measurementId: 'G-2MLLCLCLR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ5azvWAYyjI4FB8b0-0AA1OAF1JGfiuc',
    appId: '1:193960592771:android:eef154b2322942adc5a2b6',
    messagingSenderId: '193960592771',
    projectId: 'students-app-b1fa2',
    storageBucket: 'students-app-b1fa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWMwX6cF0c5J-wy1_Y8Q6bySCZQx2CnIc',
    appId: '1:193960592771:ios:3ebe23de4577eb9ac5a2b6',
    messagingSenderId: '193960592771',
    projectId: 'students-app-b1fa2',
    storageBucket: 'students-app-b1fa2.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWMwX6cF0c5J-wy1_Y8Q6bySCZQx2CnIc',
    appId: '1:193960592771:ios:3ebe23de4577eb9ac5a2b6',
    messagingSenderId: '193960592771',
    projectId: 'students-app-b1fa2',
    storageBucket: 'students-app-b1fa2.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_e96TZGXvhBeTIZxXrl0LoYga8QsGagU',
    appId: '1:193960592771:web:9cc8d4626252c170c5a2b6',
    messagingSenderId: '193960592771',
    projectId: 'students-app-b1fa2',
    authDomain: 'students-app-b1fa2.firebaseapp.com',
    storageBucket: 'students-app-b1fa2.firebasestorage.app',
    measurementId: 'G-03B0YF13V5',
  );
}
